packages/next/components/membersList/councilMembersList.js, packages/next/pages/council/members.js
=> fix: council member votes display

packages/next-common/components/menu.js, packages/next/components/referenda/vote.js
=> fix: styles misc

yarn.lock
=> fix: update socket.io-parser

packages/next-common/components/progress/index.js, packages/next-common/components/styled/theme/dark.js, packages/next-common/components/styled/theme/light.js, packages/next-common/store/reducers/chainSlice.js, packages/next-common/utils/mocks/gov2-detail.json, packages/next/components/gov2/metadata.js, packages/next/components/gov2/sidebar/index.js, packages/next/components/gov2/sidebar/status.js, packages/next/components/gov2/sidebar/tally.js, packages/next/pages/gov2/referendum/[id].js, packages/next/utils/viewfuncs.js
=> Gov2 detail stage 3

packages/next/components/gov2/sidebar/index.js, packages/next/components/gov2/sidebar/tally.js, packages/next/pages/gov2/referendum/[id].js
=> fix: gov2 tally

packages/next-common/components/summary/gov2Summary.js, packages/next-common/components/summary/gov2TrackSummary.js, packages/next-common/components/summary/styled.js, packages/next-common/services/url.js, packages/next/pages/gov2/[name].js, packages/next/pages/gov2/index.js
=> gov2 summary

packages/next-common/components/gov2/referendum/metadata/index.js, packages/next-common/components/listInfo/kvList.js, packages/next-common/components/listInfo/row.js, packages/next-common/components/proposal/index.js, packages/next/pages/gov2/referendum/[id].js
=> Gov2 metadata api

packages/next-common/components/gov2/referendum/metadata/index.js, packages/next/components/gov2/sidebar/tally.js, packages/next/components/gov2/timeline.js
=> Fix: tally support data is too long to display

packages/next-common/components/gov2/referendum/metadata/index.js
=> Gov2 fix metadata display

packages/next-common/components/gov2/referendum/metadata/index.js, packages/next-common/components/listInfo/kvList.js, packages/next-common/components/listInfo/row.js, packages/next-common/components/proposal/index.js
=> Gov2 metadata mobile

packages/next-common/utils/responsive.js, packages/next/components/gov2/sidebar/index.js, packages/next/components/gov2/sidebar/tally.js
=> Gov2 sidebar mobile css

packages/next/components/gov2/timeline.js
=> gov2 fix detail darkmode

packages/next-common/components/menu/index.js, packages/next-common/utils/gov2/index.js
=> Gov2 track menu active count

packages/next-common/components/icons/track.js
=> gov2 menu reduce hack way

packages/next-common/components/tags/state/gov2.js, packages/next-common/components/tooltip.js, packages/next-common/utils/consts/state.js, packages/next-common/utils/index.js, packages/next/components/gov2/sidebar/index.js, packages/next/components/gov2/sidebar/status.js
=> Gov2 sidebar status

packages/next-common/assets/imgs/icons/menu-fold.svg, packages/next-common/assets/imgs/icons/menu-unfold.svg, packages/next-common/components/icons/menuFold.js, packages/next-common/components/icons/menuUnFold.js, packages/next-common/components/layout/Gov2Layout.js, packages/next-common/components/menu/index.js, packages/next-common/store/reducers/settingSlice.js, packages/next-common/styles/componentCss.js, packages/next-common/utils/constants.js
=> feat: foldable menu group

packages/next-common/components/layout/content.js, packages/next-common/components/menu/index.js, packages/next-common/utils/consts/menu/gov2.js
=> Gov2 menu reiviewed

packages/next-common/components/summary/cardContent.js, packages/next-common/components/summary/gov2TrackSummary.js, packages/next-common/components/summary/styled.js, packages/next-common/styles/componentCss.js
=> Gov2 track summary new

packages/next-common/components/summary/gov2TrackSummary.js, packages/next-common/components/summary/styled.js
=> gov2 track summary enhancement

packages/next-common/components/menu/index.js
=> gov2 fix menu use effect

packages/next-common/components/gov2/trackTag.js, packages/next-common/styles/componentCss.js, packages/next/utils/viewfuncs.js
=> gov2 track tag

packages/next-common/components/post.js, packages/next-common/styles/componentCss.js
=> fix post item extra text css

packages/next-common/components/header/left/chainLogo.js, packages/next-common/utils/hooks/useIsGov2Page.js
=> gov2 separate gov1 gov2 home page header logo url

packages/next-common/utils/hooks/useIsGov2Page.js
=> fix use is gov2 page hook

packages/next-common/components/_Breadcrumb/Breadcrumb.js, packages/next-common/components/_Breadcrumb/BreadcrumbItem.js, packages/next-common/components/_Breadcrumb/README.md, packages/next-common/components/_Breadcrumb/index.js, packages/next-common/components/_Breadcrumb/types.ts, packages/next/pages/referenda/referendum/[id].js
=> gov2 breadcrumb stage 1

packages/next/utils/viewfuncs.js
=> gov2 fix post list track

packages/next-common/utils/gov2/getTrackName.js, packages/next/pages/referenda/referendum/[id].js
=> fix: gov2 breadcrumb

packages/next-common/components/TimeDuration.js, packages/next-common/components/gov2/postList/confirmCountdown.js
=> fix: post list confirm countdown

packages/next-common/components/summary/gov2TrackSummary.js
=> feat: gov2 track summary prepare period

packages/next/pages/referenda/referendum/[id].js
=> fix: gov2 detail page breadcrumb mobile

packages/next-common/utils/democracy/votes/passed/votingOf.js
Currently nested delegations are ignored in your implementation.
Let's take Kusama Ref 234 as an example:
On ref expiry wallet `GFTBZ1p9UFfn662hdbE84R9FFSkW1wHqyV8N2t27gW1fh8U` was delegating to `FnqFKGD4vy3P7S111itFG4Y8g8cf5RcCnL3QGTzbNWzePyn`. `FnqFKGD4vy3P7S111itFG4Y8g8cf5RcCnL3QGTzbNWzePyn` in turn was delegating to `HqRcfhH8VXMhuCk5JXe28WMgDDuW9MVDVNofe1nnTcefVZn`.
So when `HqRcfhH8VXMhuCk5JXe28WMgDDuW9MVDVNofe1nnTcefVZn`, delegated votes should be added for both `GFTBZ1p9UFfn662hdbE84R9FFSkW1wHqyV8N2t27gW1fh8U` and `FnqFKGD4vy3P7S111itFG4Y8g8cf5RcCnL3QGTzbNWzePyn`.
With this PR, a delegated entry for `FnqFKGD4vy3P7S111itFG4Y8g8cf5RcCnL3QGTzbNWzePyn` would first be added to the `votes` array. Where previously there was no entry available in the `directVotes` array for this wallet …
=> fix nested/multi-level delegations bug

packages/next-common/components/democracy/votesPopup/index.js, packages/next-common/components/democracy/votesPopup/tab.js
=> feat: democracy all votes pagination

packages/kintsugi-next/pages/setting/notification.js, packages/kintsugi-next/pages/setting/subscription.js, packages/next-common/components/commentList.js, packages/next-common/components/democracy/votesPopup/votesList.js, packages/next-common/components/layout/content.js, packages/next-common/components/linkedAddress.js, packages/next-common/components/membersList/techCommMembersList.js, packages/next-common/components/overview/emptyOverview.js, packages/next-common/components/postList.js, packages/next-common/components/profile/index.js, packages/next-common/components/setting/styled.js, packages/next-common/utils/constants.js, packages/next/components/gov2/sidebar/allVoteExtrinsicsPopup/voteExtrinsicList.js, packages/next/components/membersList/councilMembersList.js, packages/next/pages/setting/notification.js, packages/next/pages/setting/subscription.js
=> fix: page widths, empty overview width

packages/next-common/components/_Breadcrumb/Breadcrumb.js, packages/next-common/components/_Breadcrumb/BreadcrumbItem.js, packages/next-common/components/_Breadcrumb/types.ts, packages/next/pages/referenda/referendum/[id].js
=> feat: new breadcrumb

packages/next-common/components/_Breadcrumb/Breadcrumb.js
=> fix: breadcrumb item props

packages/next-common/components/internalDropdown/styled.js
=> fix: post content action popup position css

packages/next-common/components/displayValue.js, packages/next-common/components/post.js
=> fix: post list value

packages/next-common/components/popup/wrapper/Popup.js, packages/next-common/utils/hooks/useScrollLock.js
=> fix: disable scrolling all votes popup

packages/next-common/components/layout/Gov2Layout.js, packages/next-common/components/menu/index.js, packages/next-common/context/settings/index.js, packages/next-common/utils/consts/menu/gov2.js, packages/next-common/utils/gov2/index.js
=> feat: gov2 category menu

packages/next-common/components/header/right.js
=> fix: header network switch width 220

packages/kintsugi-next/components/referenda/vote.js
=> fix: kintsugi referendum sidebar votes css

packages/next-common/components/menu/index.js, packages/next-common/utils/consts/menu/gov2.js
=> feat: gov2 menu active count

packages/next/components/referenda/vote.js, packages/next/components/referenda/voteBar.js
=> fix: democracy referendum vote bar

packages/next/components/referenda/vote.js, packages/next/components/referenda/voteBar.js
Reverts opensquare-network/subsquare#2365
=> Revert "fix: democracy referendum vote bar"

packages/next/components/gov2/sidebar/tally.js, packages/next/components/referenda/voteBar.js
=> feat: gov2 sidebar tally show vote bar

packages/next-common/components/democracy/allVotesPopup/votesList.js, packages/next-common/components/displayValue.js, packages/next/components/gov2/sidebar/allVoteExtrinsicsPopup/voteExtrinsicList.js
only set `title` if `showTooltip=false`. close #2368
=> fix/all votes/extrnsic use title instead of tooltip

packages/next-common/components/comment/sourceTabs.js, packages/next-common/components/tab.js, packages/next/components/universalComments/index.js
#2389 
may need a `useDetail` context hook?
=> feat: detail comment counts

packages/next-common/components/summary/item.js, packages/next-common/components/summary/new.js, packages/next-common/components/summary/styled.js, packages/next/components/summary/gov2TrackSummary.js
=> refactor: summary new

packages/next-common/components/header/wrapper.js, packages/next/components/gov2/sidebar/tally/supportBar/index.js, packages/next/components/referenda/threshold.js
=> feat: gov2 tally threshold progress tooltip

packages/next/components/referenda/voteBar.js
=> fix: tally threshold align css

packages/next/components/gov2/sidebar/status/ConfirmProgress.js, packages/next/components/gov2/sidebar/status/DecisionProgress.js, packages/next/components/gov2/sidebar/status/styled.js
=> fix: status progress group css

packages/next/components/gov2/timeline.js, packages/next/pages/fellowship/referendum/[id].js
Remove the args of DecisionStarted timeline item args, not so useful
=> Add fellowship referendum timeline, #2421

packages/next-common/components/content/richTextStyleWrapper.js
=> fix: markdown hr line color

packages/next-common/components/charts/thresholdCurve/annotations.js, packages/next-common/components/charts/thresholdCurve/gov2TallyPopup.js
=> feat: points line

packages/next-common/components/cookiesConsent/index.js, packages/next-common/components/icons/closePanel.js, packages/next-common/components/layout/baseLayout.js, packages/next-common/components/layout/content.js, packages/next-common/utils/constants.js, packages/next-common/utils/viewfuncs/cookies.js
=> feat: cookies consent

packages/next-common/components/cookiesConsent/index.js, packages/next-common/components/header/networkOptions.js, packages/next-common/components/header/nodeSwitch.js, packages/next-common/components/internalDropdown/styled.js, packages/next-common/components/login/styled.js, packages/next-common/components/overview/emptyOverview.js, packages/next-common/components/popup/wrapper/Popup.js, packages/next-common/components/popup/wrapper/PopupWithoutTitle.js, packages/next-common/components/post/postCreate.js, packages/next-common/components/styled/containers/neutralPanel.js, packages/next-common/components/styled/containers/primaryCard.js, packages/next-common/components/styled/containers/secondaryCard.js
=> refactor: neutral panel

packages/next-common/components/profile/index.js
=> fix: page profile tabs layout

packages/next-common/components/links/dotreasuryLink.js, packages/next-common/components/links/thirdPartyLink.js
=> fix: page profile dotreasury icon hovering effect

packages/next-common/components/cookiesConsent/index.js, packages/next-common/components/layout/content.js, packages/next-common/npm/scrollbarWidth.js, packages/next-common/utils/constants.js, packages/next-common/utils/hooks/useScrollbarWidth.js
=> fix: main layout

packages/next/components/gov2/business/index.js
=> fix: gov2 referendum business data

packages/next-common/components/gov2/postList/confirmCountdown.js
=> hotfix: confirm height

packages/next-common/assets/imgs/icons/block-loading.svg, packages/next-common/components/checkUnFinalizedBase.js, packages/next-common/components/notFound.js, packages/next-common/components/styled/notFound.js, packages/next-common/package.json, packages/next-common/utils/post/getMetaDesc.js, packages/next/components/treasuryProposal/checkUnFinalized.js, packages/next/pages/treasury/proposal/[id].js, yarn.lock
=> Show loading page for un-finalized treasury proposal

yarn.lock
=> chore(security): yarn audit fix

packages/next-common/components/popup/wrapper/Popup.js, packages/next-common/utils/hooks/useEventListener.js, packages/next-common/utils/hooks/useKey.js
=> feat: popup escape to close

packages/next-common/components/democracy/metadata/index.js, packages/next-common/components/summary/democracySummary.js, packages/next-common/components/summary/nextLaunchTime.js, packages/next-common/utils/hooks/useBlockTime.js
=> feat: next launch time

packages/next-common/components/emailPage/email.js, packages/next-common/components/icons/checkbox.js, packages/next-common/components/login/addressLogin.js, packages/next-common/utils/constants.js, packages/next-common/utils/hooks/useAcceptCookies.js, packages/next-common/utils/hooks/useCookieValue.js
=> feat: login process

packages/next-common/components/convictionSelect.js, packages/next-common/components/select/index.js, packages/next-common/components/select/option.js
close #2571 
make it scrollable
=> fix: conviction select

packages/next-common/components/summary/democracyBeenDelegated/beenDelegatedListPopup/delegationList.js, packages/next-common/components/summary/democracyBeenDelegated/beenDelegatedListPopup/delegationSummary.js, packages/next-common/components/summary/democracyBeenDelegated/beenDelegatedListPopup/index.js
=> fix: been delegated popup UI

packages/next/components/summary/allDelegation/index.js
=> fix: move new delegate button to bottom

packages/next-common/components/summary/democracyAllBeenDelegatedPopup/allList.js
Reverts opensquare-network/subsquare#2603
=> Revert "Add link to track item in delegation popup list"

packages/next-common/components/cookiesConsent/index.js
=> hotfix: cookie consent popup position

packages/next/.babelrc, packages/next/babel.config.js
=> build: fix babel config

packages/kintsugi-next/pages/index.js, packages/next-common/components/overview/index.js, packages/next-common/components/postList.js, packages/next/pages/index.js
=> feat: overview category title link

packages/next-common/components/setting/notification/useAdvisoryCommitteeOptions.js, packages/next/components/settings/subscription/common.js, packages/next/components/settings/subscription/useAdvisoryCommitteeSubscription.js, packages/next/components/settings/subscription/useCouncilSubscription.js, packages/next/components/settings/subscription/useDemocracySubscription.js, packages/next/components/settings/subscription/useOpenGovSubscription.js, packages/next/components/settings/subscription/useTechCommSubscription.js, packages/next/components/settings/subscription/useTreasurySubscription.js, packages/next/pages/setting/subscription.js
* Implement advisory subscription UI
* Update
* Clean code
=> Implement advisory subscription UI (#2671)

packages/next-common/components/calendar/fullCalendar/monthDateCell.js
=> feat: calendar cell hover 1

packages/kintsugi-next/pages/_app.js, packages/kintsugi-next/pages/calendar.js, packages/next-common/components/calendar/fullCalendar/index.js, packages/next/pages/_app.js
=> feat: calendar kintsugi

packages/next-common/components/calendar/dayEvents/index.js, packages/next-common/components/calendar/dayEvents/timelines.js, packages/next-common/components/calendar/fullCalendar/index.js, packages/next-common/hooks/calendar.js
=> feat: day events loading, no data

packages/next-common/components/calendar/fullCalendar/index.js, packages/next-common/components/calendar/fullCalendar/monthHeader.js
=> fix: calendar header label mobile

packages/next-common/components/calendar/fullCalendar/monthDateCell.js
=> fix: month cell label

packages/next-common/components/calendar/dayEvents/eventInfoCard/title.js, packages/next-common/components/calendar/dayEvents/eventInfoCard/utils.js, packages/next-common/styles/tailwindcss.js
=> fix: event card title effects

packages/next-common/components/popup/wrapper/Popup.js, packages/next-common/components/summary/democracyAllBeenDelegatedPopup/allList.js, packages/next-common/components/summary/democracyAllBeenDelegatedPopup/index.js, packages/next-common/components/summary/democracyAllMyDelegationPopup/index.js, packages/next-common/components/summary/democracyAllMyDelegationPopup/list.js, packages/next-common/components/summary/democracyBeenDelegated/beenDelegatedListPopup/delegationList.js, packages/next-common/components/summary/democracyBeenDelegated/beenDelegatedListPopup/index.js, packages/next-common/utils/responsive.js
=> fix: delegate popup responsive

.gitignore, .husky/pre-commit, package.json, yarn.lock
fix: husky hooks to workspace since eslint config (#2715)
=> sync husky commit from `feat-calendar`

packages/next-common/components/summary/democracyBeenDelegated/beenDelegatedInfo.js, packages/next-common/components/summary/democracyBeenDelegated/index.js, packages/next-common/components/summary/democracySummaryDelegation/democracySummaryDelegationInfo.js, packages/next-common/components/summary/democracySummaryDelegation/index.js
close #2732 
now scrollable for both
=> fix: delegation items responsive scroll

packages/next-common/components/header/left/chainLogo.js, packages/next-common/components/post.js
=> hotfix: UI issues

packages/next-common/components/fellowship/breadcrumb.js, packages/next/components/summary/gov2TrackSummary.js, packages/next/pages/fellowship/track/[id].js, packages/next/pages/referenda/track/[id].js
=> feat: distinguish gov2 referenda and fellowship text

packages/next-common/components/header/searchInputShortcut.js
=> hotfix: search input shortcut

packages/next-common/components/fellowship/breadcrumb.js, packages/next-common/components/gov2/trackTag.js, packages/next-common/components/popup/fields/trackField.js, packages/next-common/components/referenda/breadcrumb.js, packages/next-common/components/summary/democracyAllBeenDelegatedPopup/allList.js, packages/next-common/components/summary/democracyAllMyDelegationPopup/list.js, packages/next-common/utils/gov2/index.js, packages/next-common/utils/gov2/title.js, packages/next-common/utils/viewfuncs/treasury/getTreasuryProposalTitle.js, packages/next/components/gov2/timeline.js, packages/next/pages/fellowship/track/[id].js, packages/next/pages/referenda/track/[id].js
=> refactor: use `startCase` instead of `parseGov2TrackName`

packages/next-common/components/menu/index.js, packages/next-common/context/settings/index.js, packages/next-common/utils/consts/menu/index.js
=> feat: menu, default expand or collapse

packages/next-common/components/input.js, packages/next-common/components/inputNumber.js, packages/next-common/components/publicProposal/second/index.js, packages/next-common/components/publicProposal/second/popup/index.js, packages/next-common/components/publicProposal/second/popup/inputTimes.js, packages/next-common/components/publicProposal/second/popup/submitButton.js, packages/next-common/components/publicProposal/second/useMaxDeposits.js
=> feat: second process times input

packages/next-common/components/inputNumber.js
=> feat: enhance input number

packages/next-common/components/referenda/tally/styled.js, packages/next/components/gov2/sidebar/tally/index.js, packages/next/components/gov2/sidebar/tally/values/support.js, packages/next/components/gov2/sidebar/tally/values/symbolValue.js
=> hotfix: tally, mobile, support percentage

packages/next-common/components/SEO.js, packages/next-common/components/nextSeo/buildTags.js
=> hotfix(seo): twitter social media card

packages/next-common/context/theme/index.js, packages/next-common/lib/index.js, packages/next-common/package.json, packages/next-common/utils/hooks/usePreferredColorScheme.js, yarn.lock
=> feat: system appearance v1

packages/kintsugi-next/package.json, packages/next/package.json, yarn.lock
=> Add dependency sharp for image optimization, #2820

packages/next/components/childBounty/claim/index.js
=> hotfix: child bounty overview css

packages/next-common/components/statistics/referenda/beenDelegatedPopup/delegationTabList.js, packages/next-common/components/statistics/referenda/beenDelegatedPopup/index.js
=> fix: statistics been delegated popup width

packages/next-common/components/statistics/referenda/referendaDelegatee/index.js
=> fix: statistics delagatee width

packages/next-common/components/democracy/flattenedVotesPopup/index.js, packages/next-common/components/democracy/nestedVotesPopup/index.js, packages/next-common/components/popup/baseVotesPopup.js, packages/next-common/components/popup/nestedVotesPopup/delegatedDetail.jsx, packages/next/components/gov2/sidebar/callsVotesPopup/index.js, packages/next/components/gov2/sidebar/tally/flattenedVotesPopup/index.js, packages/next/components/gov2/sidebar/tally/nestedVotesPopup/index.js
=> hotfix: reduce votes popup width

packages/kintsugi-next/components/democracy/allVotesPopup/index.js, packages/kintsugi-next/components/referenda/vote.js
https://kintsugi.subsquare.io/democracy/referendum/102
=> hotfix: kintsugi check all votes popup

packages/next-common/components/styled/popupListWrapper.js, packages/next-common/components/summary/democracyAllBeenDelegatedPopup/allList.js, packages/next-common/components/summary/democracyBeenDelegated/beenDelegatedListPopup/delegationList.js
=> hotfix: summary been delegated table column width

packages/next-common/components/summary/democracyAllMyDelegationPopup/list.js
=> hotfix: my delegation table list width

packages/next-common/components/summary/democracyAllMyDelegationPopup/list.js
=> hotfix: my delegation fix user maxwidth

packages/next/components/gov2/sidebar/tally/supportBar/index.js, packages/next/components/referenda/threshold.js
=> fix: votebar, indicator position

packages/next-common/components/tooltip.jsx, packages/next/components/gov2/sidebar/status/styled.js, packages/next/components/gov2/sidebar/tally/supportBar/index.js
=> fix: tooltip, revert children wrapper css `display`

packages/next-common/components/popup/capitalTableItem.js, packages/next-common/components/styledList/index.js, packages/next-common/components/summary/democracyAllBeenDelegatedPopup/allList.js, packages/next-common/components/summary/democracyAllBeenDelegatedPopup/index.js, packages/next-common/components/summary/democracyAllMyDelegationPopup/index.js, packages/next-common/components/summary/democracyAllMyDelegationPopup/list.js, packages/next-common/components/summary/democracyBeenDelegated/beenDelegatedListPopup/delegationList.js, packages/next-common/components/summary/democracyBeenDelegated/beenDelegatedListPopup/delegationSummary.js, packages/next-common/utils/hooks/referenda/useAllBeenDelegatedList.js
=> feat: optimize my delegation and been delegated

packages/next-common/context/post/index.js
=> hotfix: sort timeline

packages/kintsugi-next/components/democracy/allVotesPopup/index.js, packages/next-common/components/democracy/flattenedVotesPopup/index.js, packages/next-common/components/democracy/nestedVotesPopup/index.js, packages/next-common/components/popup/nestedVotesPopup/delegatedDetail.jsx, packages/next-common/components/post.js, packages/next-common/components/publicProposal/second/index.js, packages/next-common/components/statistics/democracy/beenDelegatedPopup/delegationTabList.js, packages/next-common/components/statistics/referenda/beenDelegatedPopup/delegationTabList.js, packages/next-common/components/statistics/referenda/referendaDelegatee/index.js, packages/next-common/components/summary/democracyAllMyDelegationPopup/list.js, packages/next-common/components/summary/democracyBeenDelegated/beenDelegatedListPopup/delegationList.js, packages/next-common/components/user/index.js, packages/next/components/childBounty/claim/index.js, packages/next/components/fellowship/referendum/sidebar/tally/allVotesPopup/votesList.js, packages/next/components/gov2/sidebar/callsVotesPopup/index.js, packages/next/components/gov2/sidebar/tally/flattenedVotesPopup/index.js, packages/next/components/gov2/sidebar/tally/nestedVotesPopup/index.js
=> fix: user `maxWidth` design

packages/next-common/components/Descroptions/index.js, packages/next-common/components/popup/nestedVotesPopup/delegatedDetail.jsx
=> feat: optimize nested detail popup

packages/next-common/components/statistics/democracy/delegatee/index.js, packages/next-common/components/statistics/democracy/delegator/index.js, packages/next-common/components/styledList/index.js
=> fix: statistics table list border

packages/next-common/package.json, packages/next/package.json, yarn.lock
=> hotfix: bump previewer

packages/next-common/components/summary/democracyBeenDelegated/beenDelegatedListPopup/delegationList.js, packages/next-common/components/summary/democracyBeenDelegated/beenDelegatedListPopup/index.js, packages/next-common/components/summary/democracySummaryFooter.js, packages/next-common/utils/democracy/getDemocracyBeenDelegatedListByAddress.js
=> hotfix: democracy all my delegation

packages/next-common/components/popup/fields/referendaStatusSelectField.jsx, packages/next-common/components/postList.js, packages/next-common/components/select/index.js, packages/next-common/components/select/option.js, packages/next/components/gov2/gov2Page.js, packages/next/components/summary/gov2TrackSummary.js, packages/next/pages/referenda/index.js, packages/next/pages/referenda/track/[id]/index.js
=> feat: opengov referenda status filter

packages/next-common/components/postList.js, packages/next/components/gov2/gov2Page.js
=> hotfix: filter list count

packages/next-common/components/statisticsLinkButton/index.js, packages/next-common/utils/consts/settings/index.js, packages/next-common/utils/consts/settings/kusama.js, packages/next-common/utils/consts/settings/polkadot.js, packages/next/pages/treasury/bounties.js, packages/next/pages/treasury/child-bounties.js, packages/next/pages/treasury/proposals.js, packages/next/pages/treasury/tips.js
=> feat: link to dotreasury

packages/next-common/components/nav/menu.jsx, packages/next-common/context/global.js, packages/next-common/context/nav/index.jsx, packages/next-common/lib/index.js, packages/next-common/utils/constants.js
=> feat: v2 submenu visible persist

packages/next-common/store/reducers/fellowship/index.js, packages/next-common/store/reducers/fellowship/votes.js, packages/next-common/store/reducers/gov2ReferendumSlice.js, packages/next-common/utils/hooks/fellowship/useFellowshipVotes.js, packages/next/components/fellowship/referendum/sidebar/tally/allVotes.js, packages/next/components/fellowship/referendum/sidebar/tally/aye.js, packages/next/components/fellowship/referendum/sidebar/tally/index.js, packages/next/components/fellowship/referendum/sidebar/tally/loadingCount.js, packages/next/components/fellowship/referendum/sidebar/tally/nay.js
Also fixed a bug that referenda referendum show votes count 0 when enter from referenda list page.
=> Show fellowship votes count on tally

packages/next-common/components/header/nodeSwitch.js, packages/next-common/components/header/v2/index.jsx
=> fix: node switch dropdown width

packages/kintsugi-next/package.json, packages/next-common/package.json, packages/next/package.json, packages/next/pages/alliance/members.js, yarn.lock
https://github.com/opensquare-network/subsquare/security/dependabot/30
=> chore: up eslint and fix security

.github/workflows/ci.yml
=> ci: speed up

packages/next-common/components/buttons/colorButton.js, packages/next-common/components/buttons/dangerButton.js, packages/next-common/components/buttons/ghostButton.js, packages/next-common/components/buttons/primaryButton.js, packages/next-common/components/buttons/styled.js, packages/next-common/components/header/consts.js, packages/next-common/components/header/drawer.jsx, packages/next-common/components/header/headerAccount.js, packages/next-common/components/header/index.jsx, packages/next-common/components/header/networkOptions.js, packages/next-common/components/header/nodeSwitch.js, packages/next-common/components/header/searchInput.js, packages/next-common/components/wallet/walletOption.jsx
=> fix: ui misc

packages/next-common/components/summary/overviewSummary/index.js, packages/next-common/utils/consts/settings/kusama.js
=> Remove active count from kusama summary

tailwind.config.js
Reverts opensquare-network/subsquare#3297
=> Revert "chore: disable tailwind builtin colors"

packages/next-common/components/layout/democracyLayout/referenda.jsx, packages/next-common/components/layout/referendaLayout/index.jsx, packages/next/components/myvotes/referenda/useSubClassLocks.js, packages/next/pages/democracy/votes.js, packages/next/pages/referenda/votes.js
=> Add my votes tab to referenda and democracy page, #3313

packages/next-common/components/popup/wrapper/Popup.js
=> hotfix: popup click outside, revert #3276

packages/kintsugi-next/package.json, packages/next-common/components/user/index.js, packages/next-common/package.json, packages/next-common/utils/knownAddr.js, packages/next/package.json, yarn.lock
=> Special account view, #3165

packages/next-common/components/alliance/announcement/timeline.js, packages/next-common/components/detail/detailMultiTabs/index.jsx, packages/next-common/components/detail/detailMultiTabs/timelineModeTabs.jsx, packages/next-common/store/reducers/detailSlice.js, packages/next/components/childBounty/timeline.js, packages/next/components/external/timeline.js, packages/next/components/gov2/timeline.js, packages/next/components/motion/timeline.js, packages/next/components/publicProposal/timeline.js, packages/next/components/referenda/timeline.js, packages/next/components/tip/timeline.js, packages/next/pages/treasury/bounties/[id].js, packages/next/pages/treasury/proposals/[id].js
=> refactor: detail tabs timeline mode redux, #3331

packages/next-common/components/comment/index.js, packages/next-common/components/comment/sourceTabs.js, packages/next/components/polkassembly/comment/index.js, packages/next/components/universalComments/index.js
=> fix: comment source button position, #3378 

packages/next-common/components/progress/index.js, packages/next-common/components/progress/multiProgress.js, packages/next-common/components/tooltip.jsx
=> fix: multi progress tooltip

packages/next-common/components/charts/thresholdCurve/annotations.js, packages/next-common/components/charts/thresholdCurve/legend/gov2TallyLegend.js, packages/next-common/components/charts/thresholdCurve/utils/dataset.js
=> fix: Modify the color of dash line of current approval and support in threshold curve

packages/kintsugi-next/pages/user/[...params].js, packages/next-common/components/links/accountLinks.js, packages/next/pages/user/[...params].js
=> fix: remove ssr identity #3436

packages/kintsugi-next/pages/democracy/proposals/[id].js, packages/kintsugi-next/pages/democracy/referenda/[id].js, packages/kintsugi-next/pages/posts/[id].js, packages/kintsugi-next/pages/techcomm/proposals/[id].js, packages/kintsugi-next/pages/treasury/proposals/[id].js, packages/next-common/components/comment/item.js, packages/next-common/components/detail/common/contentWithComment.js, packages/next-common/context/post/comments.js, packages/next/components/details/contentWithUniversalComment.js, packages/next/components/motion/motionContent.js, packages/next/pages/advisory-committee/motions/[id].js, packages/next/pages/alliance/announcements/[id].js, packages/next/pages/council/motions/[id].js, packages/next/pages/democracy/externals/[id].js, packages/next/pages/democracy/proposals/[id].js, packages/next/pages/democracy/referenda/[id].js, packages/next/pages/fellowship/referenda/[id].js, packages/next/pages/financial-council/motions/[id].js, packages/next/pages/open-techcomm/proposals/[id].js, packages/next/pages/posts/[id].js, packages/next/pages/referenda/[id].js, packages/next/pages/techcomm/proposals/[id].js, packages/next/pages/treasury-council/motions/[id].js, packages/next/pages/treasury/bounties/[id].js, packages/next/pages/treasury/child-bounties/[id].js, packages/next/pages/treasury/proposals/[id].js, packages/next/pages/treasury/tips/[id].js
=> fix: show old comment after switch tab, #3447

packages/next/components/gov2/business/treasurySpend.js
=> Show all beneficiaries if there are multiple ones, #3438

yarn.lock
https://github.com/opensquare-network/subsquare/security/dependabot/34
=> fix: dependabot alert 34

packages/next-common/components/profile/votingHistory/index.js, packages/next/components/myvotes/common/votesListTitle.js
=> feat: all votes history #3472

packages/next-common/utils/viewfuncs/discussion/normalizeDiscussionListItem.js, packages/next-common/utils/viewfuncs/discussion/normalizePaListItem.js
=> feat: show discussions index,  #3460

packages/next-common/components/styled/containers/accordionCard.jsx
#3562
```jsx
<AccordionCard title="title">content</AccordionCard>
```
=> feat: Accordion Card,  #3562

packages/next-common/components/toast/toastItem.js, packages/next-common/store/reducers/toastSlice.js
=> fix: toast remove, #3570

packages/next-common/hooks/polkassembly/usePolkassemblyPostData.js, packages/next-common/package.json, packages/next-common/services/identity.js, yarn.lock
=> Use cache LRU instead of map, #3427

packages/next-common/components/gov2/referendum/metadata/refund/index.js
https://github.com/opensquare-network/subsquare/pull/3653/files#diff-fd9c5c47c22421e4e155307823bde9b67ff06e6bedb9281fccddccee489ae68aR62-R64
=> fix: metadata refund

packages/next-common/components/actions/articleActions.js, packages/next-common/components/actions/replyButton.js, packages/next-common/components/actions/styled/index.js, packages/next-common/components/articleContent.js, packages/next-common/components/contentMenu.js, packages/next-common/components/detail/common/PostContent.js, packages/next-common/components/polkassembly/actions.jsx, packages/next-common/components/polkassembly/detailItem/articleContent.js, packages/next-common/components/postDataSource.js, packages/next-common/components/shareSNS/index.js, packages/next-common/components/tabs/index.jsx, packages/next-common/components/thumbsUp/index.js
=> fix: post detail styles, #3674, #3557

packages/next-common/components/noData.jsx, packages/next-common/components/overview/activeProposals/empty.jsx, packages/next-common/components/overview/activeProposals/index.jsx
=> feat: empty recent proposals, #3694

packages/next-common/components/actions/articleActions.js, packages/next-common/components/overview/activeProposals/index.jsx, packages/next-common/components/thumbsUp/index.js
- article actions
- hide non active proposals
=> hotfix: ui

packages/next-common/components/detail/common/styled.js
=> hotfix: countdown layout

packages/next-common/components/Descriptions/index.js, packages/next-common/components/memberListTable/index.js, packages/next-common/components/valueDisplay.js, packages/next/components/membersList/councilMembersList.js
=> fix: council member list

packages/next-common/components/overview/activeProposals/referenda.js
=> fix: recent proposals referenda column

packages/next-common/components/layout/DiscussionsLayout.jsx, packages/next-common/utils/consts/menu/common.js, packages/next/pages/discussions.js, packages/next/pages/polkassembly/discussions.js
=> feat: merge discussions

packages/kintsugi-next/package.json, packages/next-common/components/multisigs/desktop/colmns.js, packages/next-common/components/multisigs/desktop/index.js, packages/next-common/components/multisigs/fields.js, packages/next-common/components/multisigs/mobile.js, packages/next-common/components/multisigs/signField.jsx, packages/next-common/package.json, packages/next/package.json, yarn.lock
=> feat: account multisig sign status

packages/next-common/utils/consts/settings/basilisk.js, packages/next-common/utils/consts/settings/khala.js, packages/next-common/utils/consts/settings/phala.js
=> fix: chain theme colors

packages/next-common/components/setting/notificationEmail.js
=> fix: auto clean verify error when click verify button

packages/next-common/components/dataList/index.jsx, packages/next-common/components/dataList/item.jsx, packages/next-common/components/fellowship/params/list.jsx, packages/next-common/components/fellowship/params/off-boardTimeout.jsx, packages/next-common/components/layout/ListLayout.jsx, packages/next-common/components/select/index.js, packages/next-common/services/url.js, packages/next-common/utils/consts/menu/fellowship.js, packages/next-common/utils/consts/settings/collectives.js, packages/next/pages/fellowship/params/index.jsx
=> feat: fellowship params

packages/next-common/components/overview/activeProposals/empty.jsx
=> fix: hide discussions button

packages/next-common/components/nav/menu/archived.jsx, packages/next-common/components/nav/menu/featured.jsx, packages/next-common/components/nav/menu/group.jsx, packages/next-common/components/nav/menu/index.jsx, packages/next-common/utils/consts/menu/index.js, packages/next-common/utils/consts/menu/treasury.js
=> feat: archive treasury tips

packages/next-common/components/overview/activeProposals/columns/discussionsForumTopics.jsx, packages/next-common/components/overview/activeProposals/columns/index.jsx, packages/next-common/components/overview/activeProposals/discussions.jsx, packages/next-common/components/overview/activeProposals/index.jsx, packages/next-common/components/postList/postTitle.js, packages/next-common/services/serverSide/forum.js, packages/next-common/services/serverSide/polkadotForum.js, packages/next-common/utils/consts/settings/kusama.js, packages/next-common/utils/consts/settings/polkadot.js, packages/next-common/utils/viewfuncs/discussion/normalizePolkadotForumTopicListItem.js, packages/next/pages/index.js
=> feat: forum topics

packages/next-common/components/fellowship/params/list.jsx, packages/next-common/components/fellowship/params/off-boardTimeout.jsx, packages/next-common/hooks/useSalaryAsset.js
=> fix: params salary value

packages/next-common/components/poll/index.js
=> Connect user can not vote on a discussion post, #3823

packages/next-common/components/overview/activeProposals/advisoryCommittee.js
=> fix: overview advisory committee init data

packages/next-common/components/overview/activeProposals/columns/discussionsRFCs.jsx, packages/next-common/components/overview/activeProposals/discussions.jsx, packages/next-common/components/overview/activeProposals/index.jsx, packages/next-common/services/overview/RFCs.js, packages/next-common/utils/consts/settings/collectives.js, packages/next-common/utils/viewfuncs/discussion/normalizeRFCsListItem.js
#3825
rest refactor work tracked in #3837
=> feat: collectives rfcs

packages/next-common/styles/markdown.css
=> fix: post content font smoothing

packages/next-common/components/dataList/index.jsx, packages/next-common/components/dataList/item.jsx, packages/next-common/components/fellowship/collective/list/columns.js
=> fix: fellowship members datalist

packages/next-common/components/Descriptions/index.js, packages/next-common/components/dataList/index.jsx, packages/next-common/components/dataList/item.jsx, packages/next-common/components/fellowship/core/feeds/blockLink.jsx, packages/next-common/components/fellowship/core/feeds/compareParamsChangesPopup.jsx, packages/next-common/components/fellowship/core/feeds/container.jsx, packages/next-common/components/fellowship/core/feeds/event.jsx, packages/next-common/components/fellowship/core/feeds/event/active.jsx, packages/next-common/components/fellowship/core/feeds/event/demoted.jsx, packages/next-common/components/fellowship/core/feeds/event/imported.jsx, packages/next-common/components/fellowship/core/feeds/event/inactive.jsx, packages/next-common/components/fellowship/core/feeds/event/inducted.jsx, packages/next-common/components/fellowship/core/feeds/event/offboarded.jsx, packages/next-common/components/fellowship/core/feeds/event/paramsChanged.jsx, packages/next-common/components/fellowship/core/feeds/event/promoted.jsx, packages/next-common/components/fellowship/core/feeds/event/promotion.jsx, packages/next-common/components/fellowship/core/feeds/event/proved.jsx, packages/next-common/components/fellowship/core/feeds/event/rentention.jsx, packages/next-common/components/fellowship/core/feeds/event/retained.jsx, packages/next-common/components/fellowship/core/feeds/event/shared.jsx, packages/next-common/components/fellowship/core/feeds/list.jsx, packages/next-common/components/fellowship/core/feeds/time.jsx, packages/next-common/services/url.js, packages/next/pages/fellowship/core/feeds.js
=> feat: feeds ui

packages/next-common/components/myDeposits/preimages.jsx
=> fix: profile preimages layout

packages/next-common/components/noData.jsx, packages/next-common/components/pages/fellowship/candidates.js, packages/next-common/components/pages/fellowship/empty.jsx, packages/next-common/components/pages/fellowship/loadable.js, packages/next-common/components/pages/fellowship/members.js
=> fix: fellowship member empty status

packages/next-common/components/popup/fields/convictionField.js, packages/next-common/styles/globals.css
=> fix: conviction field explanation

packages/next-common/components/dataList/item.jsx, packages/next-common/components/fellowship/salary/cycles/history/expenditure.jsx, packages/next-common/components/fellowship/salary/cycles/history/registerPaid.jsx, packages/next-common/components/fellowship/salary/cycles/history/timeRange.jsx, packages/next-common/components/fellowship/salary/cycles/list.js, packages/next-common/components/valueDisplay.js
=> feat: history cycle ui

packages/kintsugi-next/package.json, packages/next-common/components/fellowship/salary/cycles/notFound.jsx, packages/next-common/package.json, packages/next-common/services/url.js, packages/next/package.json, packages/next/pages/fellowship/salary/cycles/[...params].jsx, yarn.lock
=> feat: cycle detail, 404

packages/next-common/components/fellowship/salary/cycles/info/closed.jsx, packages/next-common/components/fellowship/salary/cycles/summary/totalDuration.jsx
=> feat: cycle detail info, closed summary items

packages/next-common/components/fellowship/salary/cycles/info/closed.jsx, packages/next-common/components/fellowship/salary/cycles/info/ongoing.jsx, packages/next-common/components/fellowship/salary/cycles/info/progress.jsx, packages/next-common/components/progress/multiProgress.js
=> feat: cycle detail paid progress

packages/next-common/components/fellowship/salary/cycles/tabsList/feeds.jsx, packages/next-common/components/fellowship/salary/cycles/tabsList/index.jsx, packages/next-common/components/fellowship/salary/cycles/tabsList/registrations.jsx, packages/next-common/components/fellowship/salary/cycles/tabsList/template.jsx
=> fix: cycle detail tabs, effective persist

packages/next-common/components/fellowship/salary/cycles/tabsList/payments.jsx, packages/next-common/components/myDeposits/treasury/bounties.jsx, packages/next-common/components/tags/checkable.jsx
=> refactor: checkable tag

packages/next-common/components/fellowship/salary/cycles/tabsList/columns/payment.jsx, packages/next-common/components/fellowship/salary/cycles/tabsList/registrations.jsx
=> fix: cycle registrations payment mobile

packages/next-common/components/delegation/delegate/referenda/card.js, packages/next-common/components/democracy/delegatePopup/target.js, packages/next-common/components/gov2/delegatePopup/index.js, packages/next-common/components/gov2/delegatePopup/moonPopup.js, packages/next-common/components/gov2/delegatePopup/popupContent.js, packages/next-common/components/summary/allDelegation/newDelegateButton.js
=> feat: delegation card new delegate button

packages/next-common/components/delegation/delegate/referenda/avatar.jsx, packages/next-common/components/delegation/delegate/referenda/card.js, packages/next-common/components/delegation/delegate/referenda/detailPopup.jsx, packages/next-common/components/delegation/delegate/referenda/summary.jsx
=> feat: delegation init detail popup

packages/next-common/components/delegation/delegate/referenda/detailPopup/index.jsx, packages/next-common/components/delegation/delegate/referenda/detailPopup/tabsContent/beenDelegated.jsx, packages/next-common/components/delegation/delegate/referenda/detailPopup/tabsContent/index.jsx
=> feat: delegation, been delegated list

packages/next-common/components/delegation/delegate/referenda/detailPopup/tabsContent/beenDelegated/delegatorList.jsx, packages/next-common/components/delegation/delegate/referenda/detailPopup/tabsContent/beenDelegated/index.jsx, packages/next-common/components/delegation/delegate/referenda/detailPopup/tabsContent/beenDelegated/info.jsx, packages/next-common/components/summary/democracyBeenDelegated/beenDelegatedListPopup/delegationList.js
=> feat: delegation tab been delegated detail

packages/next-common/components/delegation/delegate/referenda/card.js, packages/next-common/components/links/accountLinks.js
=> fix: delegation card hide councilor link

packages/next-common/components/delegation/delegate/delegatesSection.js, packages/next-common/components/delegation/delegate/democracy/card.jsx, packages/next-common/components/delegation/delegate/democracy/detailPopup/index.jsx, packages/next-common/components/delegation/delegate/democracy/detailPopup/tabsContent/beenDelegated/index.jsx, packages/next-common/components/delegation/delegate/democracy/detailPopup/tabsContent/index.jsx, packages/next-common/components/delegation/delegate/democracy/index.jsx, packages/next-common/components/delegation/delegate/democracy/members.jsx, packages/next-common/components/delegation/delegate/democracy/summary.jsx, packages/next-common/components/democracy/delegatePopup/index.js, packages/next-common/components/democracy/delegatePopup/moonPopup.js, packages/next-common/components/democracy/delegatePopup/popupContent.js, packages/next-common/components/summary/democracySummaryDelegation/newDelegation.js, packages/next-common/store/reducers/democracy/delegates.js, packages/next-common/store/reducers/democracy/index.js
=> feat: delegation democracy

packages/next-common/components/delegation/delegate/democracy/card.jsx, packages/next-common/components/delegation/delegate/democracy/detailPopup/actions.jsx, packages/next-common/components/delegation/delegate/democracy/detailPopup/index.jsx, packages/next-common/components/summary/democracySummaryDelegation/newDelegation.js
=> feat: delegation, democracy actions

packages/next-common/components/delegation/delegate/democracy/card.jsx
=> fix: delegation, democracy, hide new delegate button

packages/next-common/components/delegation/delegate/myDelegationSection/allDelegationCard.jsx
=> fix: delegation, my delegation api call

packages/next-common/components/delegation/delegate/myDelegationSection/allDelegationCard.jsx
=> fix: delegation, detail link

packages/next-common/components/overview/accountInfo/accountInfoPanel.js, packages/next-common/components/overview/accountInfo/components/delegationPrompt.jsx, packages/next-common/components/overview/accountInfo/noLinkAddress.js, packages/next-common/components/overview/accountInfo/notLoginPanel.js, packages/next-common/utils/constants.js, packages/next-common/utils/consts/menu/common.js
=> feat: delegation prompt

packages/next-common/components/delegation/delegate/common/sortSelect.jsx, packages/next-common/components/delegation/delegate/democracy/index.jsx, packages/next-common/components/delegation/delegate/referenda/index.js, packages/next-common/components/pagination/usePaginationComponent.js, packages/next-common/store/reducers/democracy/delegates.js, packages/next-common/store/reducers/referenda/delegates.js
=> feat: delegation, add sort select

packages/next-common/components/addressCombo.js
=> feat: delegation, address select add invalid message

packages/next-common/utils/consts/menu/fellowship.js
=> fix: fellowship menu highlighted

packages/next-common/components/popup/wrapper/Popup.js
=> fix: popup close icon color

packages/next-common/components/header/searchInput.js, packages/next-common/components/input.js, packages/next-common/components/proposal/index.js
=> fix: ui review

packages/next-common/components/fellowship/salary/claimants/consts.js, packages/next-common/components/fellowship/salary/claimants/consts.jsx, packages/next-common/components/fellowship/salary/claimants/container.jsx, packages/next-common/components/fellowship/salary/claimants/isRegistered.jsx, packages/next-common/components/fellowship/salary/claimants/list.jsx, packages/next-common/components/fellowship/salary/claimants/status.jsx, packages/next-common/components/fellowship/salary/common.js, packages/next-common/hooks/fellowship/salary/useFellowshipSalaryStatusFilter.jsx, packages/next-common/hooks/fellowship/useRankFilter.js, packages/next-common/services/url.js, packages/next-common/utils/consts/menu/fellowship.js, packages/next/pages/fellowship/salary/claimants/index.jsx
=> feat: fellowship salary claimants

packages/next-common/components/fellowship/salary/common.js, packages/next-common/components/fellowship/salary/summary.jsx, packages/next-common/services/serverSide/fellowship/common.js, packages/next/pages/fellowship/salary/claimants/index.jsx, packages/next/pages/fellowship/salary/cycles/[...params].jsx, packages/next/pages/fellowship/salary/feeds.js, packages/next/pages/fellowship/salary/index.js
=> feat: add salary summary content

packages/next-common/components/delegation/delegate/democracy/card.jsx, packages/next-common/components/delegation/delegate/myDelegationSection/publicAnnouncement/announcement.jsx, packages/next-common/components/delegation/delegate/myDelegationSection/publicAnnouncement/democracy.jsx, packages/next-common/components/delegation/delegate/myDelegationSection/publicAnnouncement/index.jsx, packages/next-common/components/delegation/delegate/myDelegationSection/publicAnnouncement/referenda.jsx, packages/next-common/components/delegation/delegate/referenda/card.js
=> feat: separate my delegate card

packages/next-common/components/fellowship/salary/claimants/list.jsx, packages/next-common/components/fellowship/salary/common.js, packages/next-common/components/fellowship/salary/summary.jsx, packages/next-common/hooks/fellowship/salary/useFellowshipSalaryClaimantsData.js, packages/next-common/hooks/fellowship/salary/useFetchFellowshipSalaryClaimants.js, packages/next-common/store/reducers/fellowship/claimants.js, packages/next-common/store/reducers/fellowship/index.js
=> fix: salary claimants data source

packages/next-common/components/fellowship/collective/list/index.js, packages/next-common/components/whales/columns/addressCol.jsx
=> fix: address col width

packages/next-common/components/comment/voteTag/referendaVoteTag/index.js, packages/next-common/components/detail/detailMultiTabs/index.jsx, packages/next-common/components/statistics/referenda/proposalAddress/accountsConvictionUsedContent.jsx, packages/next-common/components/statistics/referenda/proposalAddress/accountsRingChart.jsx, packages/next-common/components/statistics/referenda/proposalAddress/accountsVotesChart.jsx, packages/next-common/components/statistics/referenda/proposalAddress/accountsVotesContent.jsx, packages/next-common/components/statistics/referenda/proposalAddress/headNotes.jsx, packages/next-common/components/statistics/referenda/proposalAddress/index.jsx, packages/next-common/components/statistics/referenda/proposalAddress/statisticsContent.jsx, packages/next-common/components/statistics/referenda/proposalAddress/style.js, packages/next-common/components/statistics/referenda/proposalAddress/totalVoteContent.jsx, packages/next-common/components/statistics/referenda/proposalAddress/voteChart.jsx, packages/next-common/components/tabs/tabsList.jsx, packages/next-common/package.json, packages/next-common/utils/index.js, packages/next/pages/referenda/[id].js, yarn.lock
…tes,' and 'Accounts Conviction Used' modules.
=> feat: Implement charts(only UI) for referendum statistics

packages/next-common/components/whales/currentList.jsx, packages/next-common/components/whales/historyList.jsx
=> fix: whales ui

packages/next-common/components/statistics/referenda/proposalAddress/accountsVotesChart.jsx, packages/next-common/components/statistics/referenda/proposalAddress/accountsVotesContent.jsx, packages/next-common/components/statistics/referenda/proposalAddress/useRangedVotesData.js
=> fix: detail statistics, accounts votes

packages/next-common/components/detail/detailMultiTabs/index.jsx
=> feat: detail, persist tab

packages/next-common/components/fellowship/core/members/card.js, packages/next-common/components/icons/signalIndicator.jsx
=> fix: signal indicator icon

packages/next-common/components/tooltip.jsx
=> fix: tooltip value display symbol color

packages/next-common/components/overview/accountInfo/accountInfoPanel.js, packages/next-common/components/overview/accountInfo/components/delegationPrompt.jsx, packages/next-common/components/overview/accountInfo/components/useDelegationPrompt.js, packages/next-common/components/overview/accountInfo/components/useSetAvatarPrompt.js, packages/next-common/components/scrollPrompt/index.js, packages/next-common/package.json, packages/next-common/utils/constants.js, packages/next-common/utils/hooks/useCookieValue.js, yarn.lock
=> Add an avatar setting prompt on the account panel, #4159

packages/next-common/components/comment/item.js
=> Nested comments is not updated immediately after edit, #4245

packages/next-common/components/nav/menu/common.jsx, packages/next-common/components/nav/menu/featured.jsx, packages/next-common/components/nav/menu/group.jsx, packages/next-common/components/nav/menu/item.jsx, packages/next-common/components/overview/recentProposals/fellowship.js, packages/next-common/utils/consts/menu/fellowship.js
=> feat: sub group menu

.github/workflows/ci.yml, package.json, packages/next-common/components/datePicker.js, packages/next-common/package.json, packages/next-common/utils/index.js, packages/next-common/utils/index.test.js, packages/next/next.config.js, packages/next/package.json, vitest.config.js, vitest.workspace.js, yarn.lock
=> perf: use dayjs instead of moment

packages/next-common/components/wallet/novaWallet.js, packages/next-common/hooks/connect/useSubstrateAccounts.js
=> refactor: use injected web3 extension, #4296

packages/next-common/components/callDetailPopup/index.js, packages/next-common/components/charts/votesBubble/index.jsx, packages/next-common/components/editor/index.jsx, packages/next-common/components/fellowship/salary/cycles/tabsList/template.jsx, packages/next-common/components/myDeposits/depositTemplate.jsx, packages/next-common/components/nav/index.jsx, packages/next-common/components/nav/menu/group.jsx, packages/next-common/components/overview/recentProposals/recentProposalTemplate.jsx, packages/next-common/components/preImages/preImagesList.js, packages/next-common/components/setting/pages/notification.js, packages/next-common/components/tabs/tabsList.jsx, packages/next-common/package.json, packages/next-common/utils/hooks/usePreferredColorScheme.js, yarn.lock
=> refactor: only react-use, #4268

packages/next/pages/delegation/index.js
=> perf: delegation page lazy load, #4268

packages/next-common/components/wallet/novaWallet.js, packages/next-common/components/wallet/polkadotWallet.js, packages/next-common/components/wallet/polkagateSnapWallet.jsx, packages/next-common/components/wallet/useInjectedWeb3.js, packages/next-common/components/wallet/useInjectedWeb3Extension.js, packages/next-common/hooks/connect/useSubstrateAccounts.js
=> fix: `useInjectedWeb3`, remove `loading` and fix `injectedWeb3` value  #4399 #4400

packages/next-common/components/addressCombo.js, packages/next-common/components/ambassador/core/summary/import/popup.js, packages/next-common/components/ambassador/core/summary/induct/popup.js, packages/next-common/components/assets/transferPopup/index.js, packages/next-common/components/charts/votesBubble/DVDetailPopup.jsx, packages/next-common/components/collectives/core/actions/more/submitEvidenceItem/popup.jsx, packages/next-common/components/democracy/delegatePopup/index.js, packages/next-common/components/democracy/delegatePopup/moonPopup.js, packages/next-common/components/fellowship/core/summary/import/popup.js, packages/next-common/components/fellowship/core/summary/induct/popup.js, packages/next-common/components/fellowship/salary/actions/payout/popup.jsx, packages/next-common/components/gov2/delegatePopup/index.js, packages/next-common/components/gov2/delegatePopup/moonPopup.js, packages/next-common/components/popup/fields/addressComboField.js, packages/next-common/components/preImages/createPreimagePopup/fields/useBeneficiaryField.js, packages/next-common/components/preImages/createPreimagePopup/newLocalTreasuryProposalPopup.js, packages/next-common/components/preImages/createPreimagePopup/newUSDxTreasuryProposalPopup.js, packages/next-common/components/preImages/newPreimagePopup/index.js, packages/next-common/components/publicProposal/second/popup/moonPopup.js, packages/next-common/components/summary/newDemocracyProposalPopup/index.js, packages/next-common/components/summary/newProposalButton/templates/newRemark.js, packages/next-common/components/summary/newProposalButton/templates/spendLocal.js, packages/next-common/components/summary/newProposalButton/templates/spendUSDx.js, packages/next-common/components/summary/newProposalQuickStart/createTreasuryProposalPopup/index.js, packages/next-common/components/summary/newProposalQuickStart/createUSDxTreasuryProposalPopup/index.js, packages/next-common/components/treasury/proposal/popup/index.js, packages/next-common/components/treasury/tip/popup/index.js, packages/next/components/tipper/endorsePopup.js
=> Induct UI: It is not clear that the field it editable, #4283

packages/next-common/components/wallet/polkagateSnapWallet.jsx, packages/next-common/hooks/connect/usePolkagateSnapEnabled.js, packages/next-common/hooks/useIsMobileDevice.js
=> fix: polkagate snap enabled, #4455

packages/next-common/hooks/connect/useSubstrateAccounts.js, packages/next-common/utils/constants.js, packages/next-common/utils/withTimeout.js
=> fix: polkadot wallet extension timeout #4460

packages/next-common/components/wallet/options/substrate/index.jsx, packages/next-common/components/wallet/options/substrate/multiSig.jsx, packages/next-common/hooks/connect/useSubstrateWallets.js
=> fix: multiSig typo #4416

packages/next-common/components/popupWithSigner/maybePolkadotSigner.js, packages/next-common/hooks/connect/useSubstrateAccounts.js, packages/next-common/hooks/connect/useSubstrateInjectedAccounts.js
=> fix: revert `useSubstrateAccounts` `defaultLoading` to avoid flicker `new proposal` #4476

packages/next-common/components/collectives/core/member/demotionPeriod.js, packages/next-common/components/collectives/core/member/promotionPeriod.js, packages/next-common/components/remaining.jsx
Issue link: https://github.com/opensquare-network/subsquare/issues/4337
=> PR: feat: enhance the display of promotion/demotion period

packages/next-common/components/charts/thresholdCurve/legend/gov2TallyLegend.js, packages/next-common/components/charts/thresholdCurve/utils/dataset.js, packages/next-common/components/charts/thresholdCurve/utils/options.js
Issue link: https://github.com/opensquare-network/subsquare/issues/4207
=> Swap the line style of Threshold and Current #4207

packages/next-common/components/fellowship/statistics/expenditure/claimants/columns/claimant.jsx, packages/next-common/components/fellowship/statistics/expenditure/claimants/columns/cycles.jsx, packages/next-common/components/fellowship/statistics/expenditure/claimants/columns/paid.jsx, packages/next-common/components/fellowship/statistics/expenditure/claimants/columns/rank.jsx, packages/next-common/components/fellowship/statistics/expenditure/claimants/index.jsx, packages/next-common/components/fellowship/statistics/expenditure/cycles/barChart/utils.js, packages/next-common/components/fellowship/statistics/expenditure/summary/index.jsx
=> feat: add Fellowship Statistics.

packages/next-common/components/fellowship/statistics/collectives.jsx, packages/next-common/components/fellowship/statistics/common.js, packages/next-common/components/fellowship/statistics/expenditure/claimants/columns/claimant.jsx, packages/next-common/components/fellowship/statistics/expenditure/claimants/columns/cycles.jsx, packages/next-common/components/fellowship/statistics/expenditure/claimants/columns/paid.jsx, packages/next-common/components/fellowship/statistics/expenditure/claimants/columns/rank.jsx, packages/next-common/components/fellowship/statistics/expenditure/claimants/index.jsx, packages/next-common/components/fellowship/statistics/expenditure/common.js, packages/next-common/components/fellowship/statistics/expenditure/cycles/barChart/index.jsx, packages/next-common/components/fellowship/statistics/expenditure/cycles/barChart/utils.js, packages/next-common/components/fellowship/statistics/expenditure/cycles/cyclesChart.jsx, packages/next-common/components/fellowship/statistics/expenditure/cycles/index.jsx, packages/next-common/components/fellowship/statistics/expenditure/index.jsx, packages/next-common/components/fellowship/statistics/expenditure/rank/doughnutChart/index.jsx, packages/next-common/components/fellowship/statistics/expenditure/rank/doughnutChart/labels.jsx, packages/next-common/components/fellowship/statistics/expenditure/rank/index.jsx, packages/next-common/components/fellowship/statistics/expenditure/summary/index.jsx, packages/next-common/components/fellowship/statistics/membership/index.jsx, packages/next-common/components/fellowship/statistics/membership/rankDistribution/doughnutChart/index.jsx, packages/next-common/components/fellowship/statistics/membership/rankDistribution/doughnutChart/labels.jsx, packages/next-common/components/fellowship/statistics/membership/rankDistribution/index.jsx, packages/next-common/components/fellowship/statistics/membership/summary/index.jsx, packages/next-common/components/fellowship/statistics/membership/summary/summaryItems.jsx, packages/next-common/hooks/fellowship/useFellowshipParams.js, packages/next-common/services/url.js, packages/next-common/utils/consts/menu/common/collectives.js, packages/next-common/utils/consts/menu/fellowship.js, packages/next/pages/fellowship/statistics/index.jsx
=> feat: fellowship statistics #4329

packages/next-common/components/popup/fields/blocksField.js, packages/next-common/components/popup/fields/validFromField.js, packages/next-common/components/preImages/createPreimagePopup/fields/useValidFromField.js, packages/next-common/components/summary/newProposalQuickStart/common/advanceSettings.js
=> Enhance valid_from UI on USDx spend proposal #4579

packages/kintsugi-next/components/referenda/popup/index.js, packages/next/components/fellowship/referendum/votePopup/index.js, packages/next/components/motion/vote/popup/popupContent.js
=> Fix useSendTransaction object wrong destruction, 4601

packages/next-common/components/linkPost/postLinkPopup/index.js, packages/next-common/components/linkPost/styled.js, packages/next-common/components/popup/wrapper/Popup.js, packages/next-common/components/preImages/createPreimagePopup/index.js, packages/next-common/components/summary/newProposalButton/common.js
- fix the font size
- fix the item style
=> fix: optimize styles, #4650

packages/next-common/components/detail/treasury/spend/metadata.js, packages/next-common/components/overview/recentProposals/columns/index.jsx, packages/next-common/components/postList/post.jsx, packages/next-common/hooks/treasury/spend/useTreasurySpendRequest.js, packages/next-common/utils/treasury/spend/beneficiary.js, packages/next-common/utils/treasury/spend/getAssetByMetaV3.js, packages/next-common/utils/treasury/spend/getAssetByMetaV4.js, packages/next-common/utils/treasury/spend/knownPolkadotAssetHubAssets.js, packages/next-common/utils/treasury/spend/usdCheck.js
=> Support treasury spend info extraction by XCM v4, #4693

packages/next-common/components/collective/metadata/marketMetadata.js, packages/next-common/components/detail/treasury/spend/metadata.js, packages/next-common/components/detail/treasury/spend/payout/index.js, packages/next-common/components/detail/treasury/spend/payout/paidInfo.js, packages/next-common/components/howOpenGovWorks.js, packages/next-common/components/identityTimeline/timeline/link.js
Also, we show a hint that a spend has been paid.
=> Add beneficiary external link on treasury spend page, #4702

packages/next-common/components/deletePopup/index.js, packages/next-common/styles/tailwind-plugins/fonts.js, packages/next-common/styles/tailwind-plugins/scrollbar.js, packages/next-common/styles/tailwind.css, packages/next-common/utils/index.cn.test.js, packages/next-common/utils/index.js, packages/next-common/utils/tailwind/tailwindMerge.js, tailwind.config.js
=> improve tailwind DX #4707

packages/next-common/components/popup/wrapper/container.jsx, tailwind.config.js
This reverts commit d951a0d8b7b3549d91d68a41ee47c88c97734d1f.
=> revert: tailwind colors #4707

packages/next/pages/treasury/tips/[id].js, packages/next/pages/treasury/tips/index.js
=> hotfix: treasury tips page collective context #4662

packages/next/components/council/membersNoElections.js, packages/next/pages/advisory-committee/members.js, packages/next/pages/community-council/members.js, packages/next/pages/financial-council/members.js, packages/next/pages/techcomm/members.js
=> fix: archived collective members page loading #4719

packages/next-common/components/assets/crossChainTransferPopup/index.js, packages/next-common/components/overview/accountInfo/hook/useAccountTransferPopup.jsx
And not check whether the target is the sender itself.
=> Correct transfer tx, #4746

packages/next-common/hooks/useSendTransaction.js, packages/next-common/utils/sendTransaction/sendSubstrateTx.js
…#4659)"
This reverts commit 9636a07929fe3c5c80ede879b6f583a0fd3ea615.
=> Revert "fix: evidence submission does not work with talisman, #4639

packages/next-common/components/layout/baseLayout.jsx, packages/next-common/components/summary/polkadotTreasurySummary/relayChainTreasury/spendPeriodCountdown.jsx
=> fix: ui #4818

packages/next-common/components/summary/newCouncilMotionProposalButton/common/submitCouncilMotionProposalPopupCommon.jsx, packages/next-common/components/summary/newCouncilMotionProposalButton/common/treasuryProposalPopupContent.jsx, packages/next-common/components/summary/newCouncilMotionProposalButton/newCouncilMotionProposalPopup.jsx, packages/next-common/components/summary/newCouncilMotionProposalButton/rejectTreasuryProposalInnerPopup.jsx
=> Add rejectProposal template and enable proposal templates for council, #4979

packages/next-common/hooks/usePostCommentsFilteredData.js
=> Skip api call for incorrect comment address, #5077

packages/next-common/components/assets/tabs/index.jsx, packages/next-common/components/myDeposits/depositTemplate.jsx, packages/next-common/components/tabsList/index.js, packages/next/components/myvotes/common/votesListTitle.js, packages/next/components/myvotes/referenda/votes/index.js
This reverts commit ba92b5bf1d6d3ac0e3fc043498836eaae89652c0.
=> Revert "fix: tabs component a11y (#5115)"

packages/kintsugi-next/pages/democracy/proposals/index.js, packages/next-common/components/publicProposal/metadata.js
Show vote symbol on public proposal deposits
=> Not show escrow if not login

packages/kintsugi-next/components/democracy/allVotesPopup/index.js, packages/next-common/components/charts/votesBubble/bubbleContent.jsx, packages/next-common/components/charts/votesBubble/dv/card.jsx, packages/next-common/components/collectives/core/member/avatarAndAddress.js, packages/next-common/components/democracy/democracyCallsVotesPopup/index.js, packages/next-common/components/democracy/flattenedVotesPopup/index.js, packages/next-common/components/democracy/nestedVotesPopup/index.js, packages/next-common/components/fellowship/core/members/tabs/index.js, packages/next-common/components/popup/nestedVotesPopup/delegationsList.jsx, packages/next-common/components/summary/democracyBeenDelegated/beenDelegatedListPopup/delegationList.js, packages/next-common/components/user/addressUser.js, packages/next-common/components/user/polkassemblyUser.js, packages/next-common/components/user/styled.js, packages/next-common/components/user/subIdentityUser.js, packages/next-common/components/user/systemUser.js, packages/next-common/components/whales/columns/addressCol.jsx, packages/next/components/fellowship/referendum/sidebar/tally/allVotesPopup/index.js, packages/next/components/fellowship/referendum/sidebar/tally/fellowshipCallsVotesPopup/index.js, packages/next/components/gov2/sidebar/tally/flattenedVotesPopup/index.js, packages/next/components/gov2/sidebar/tally/nestedVotesPopup/accountCell.jsx, packages/next/components/gov2/sidebar/tally/openGovCallsVotesPopup/index.js, packages/next/components/myvotes/democracy/delegatedVotes/hint.js
close #5205 , add a new prop `link` instead of `linkToVotesPage` `linkToFellowshipPage`
=> refactor: <addressUser /> link props #5205

packages/next-common/components/tabs/list/item.jsx
=> fix: tabs list item style

packages/next-common/hooks/nav/useNavLogoEventBackgroundSrc.js
assign value at runtime, not buildtime
=> fix: nav logo event `nowDay` value

packages/next-common/components/currencyInput/index.jsx, packages/next-common/lib/input/index.jsx, packages/next-common/lib/input/number/index.d.js, packages/next-common/lib/input/number/index.jsx, packages/next-common/lib/input/number/utils.js
=> fix(lib): number input, handle `onblur` event #5323

packages/next-common/components/billBoardPanel.js, packages/next-common/components/pages/fellowship/viewModeSwitch.js
=> fix fellowship members page ui issues #5362

packages/next-common/components/tabs/list/index.jsx
=> fix: tabs list item active highlight #5319

packages/next-common/hooks/treasury/bounty/useBountyBond.js
=> fix: new bounty bond error #5417

packages/next-common/components/copyable.js, packages/next-common/components/overview/accountInfo/components/collapsePanel.jsx, packages/next-common/components/profile/OpenGovBio/index.jsx, packages/next-common/components/profile/OpenGovBio/votesPower/index.jsx, packages/next-common/components/profile/OpenGovBio/votesPower/panel.jsx, packages/next-common/components/profile/OpenGovBio/votesPower/valueDisplay.jsx, packages/next-common/components/profile/bio.js, packages/next-common/components/profile/democracyBio/votesPower/index.jsx
CollapsePanel icon switch
copyicon align middle
profile style
=> Modify the layout of profile with votes power, #5601

packages/next-common/components/collectives/core/member/demotionPeriod.js, packages/next-common/components/collectives/core/member/promotionPeriod.js, packages/next-common/components/fellowship/params/period.js, packages/next-common/components/pages/fellowship/member/fellowshipMember/membership.js
=> Add membership card on member detail page, #5616

packages/next-common/components/fellowship/core/memberWarnings/candidates.jsx
=> fix: missing candidate param, #5637

packages/next-common/hooks/usePostCommentsFilterByAddressIdentity.js
=> fix: catch error and close loading with address identity

packages/next-common/components/header/hooks/useDetectDevice.js, packages/next-common/components/header/search/popup/index.js, packages/next-common/components/popup/wrapper/Popup.js
…efactoring of the popup code, #5781
=> feat: the adaptive width of pop-up on pc and mobile and the partial refactoring of the popup code, #5781

packages/collectives-next/pages/treasury/child-bounties/[id].js, packages/next-common/api/disabledApi.js, packages/next-common/components/calendar/createEventModal/index.js, packages/next-common/components/commentSimple.js, packages/next-common/components/header/search/common/commonList.js, packages/next-common/components/layout/DetailLayout/useBreadcrumbs.js, packages/next-common/components/linkPost/postLinkPopup/index.js, packages/next-common/components/pages/components/childBounty/checkUnFinalized.js, packages/next-common/components/poll/index.js, packages/next-common/components/treasury/bounty/newChildBountyPopup.jsx, packages/next-common/noSima/actions/comment.js, packages/next-common/sima/actions/appendant.js, packages/next-common/sima/actions/comment.js, packages/next-common/utils/viewfuncs/index.js
=> Should unique index child bounty with two fields parentBountyId and index, #6060

packages/next-common/components/addressInfo.jsx, packages/next-common/components/coretime/salePanel/chart/index.jsx, packages/next-common/components/coretime/salePanel/chart/periodProgress.jsx, packages/next-common/components/coretime/salePanel/chart/skeleton.jsx, packages/next-common/components/coretime/salePanel/chart/statistics/index.jsx, packages/next-common/components/editor/loading.js, packages/next-common/components/fellowship/salary/cycles/current/loadingSkeleton.js, packages/next-common/components/header/search/popup/loadingSkeleton.js, packages/next-common/components/login/web3/walletconnect.jsx, packages/next-common/components/pages/fellowship/member/fellowshipMember/evidenceWish.js, packages/next-common/components/pages/fellowship/member/fellowshipMember/membership.js, packages/next-common/components/skeleton.js
- Fix the skeleton loading effect in dark mode
- Use global Skeleton compnent replace custom Skeleton compnent
=> Fix the skeleton loading effect in dark mode, #6201

packages/next-common/components/postList/fellowshipReferendaPostList/index.jsx, packages/next-common/components/postList/fellowshipReferendaPostList/postItem.jsx, packages/next-common/components/postList/fellowshipReferendaPostList/postItemVotesSummary.jsx, packages/next-common/components/postList/myVoteMark/index.jsx, packages/next-common/components/postList/post.jsx, packages/next-common/components/profile/posted/list.js, packages/next-common/pages/fellowship/index.js, packages/next-common/pages/fellowship/tracks/[id].js
- fellowship refrenda page use FellowshipReferendaPostList
- fellowship track page use FellowshipReferendaPostList
- user profile page posted tab fellowship type use FellowshipReferendaPostList
=> Refactor fellowship referenda postlist component, #6311 

packages/next-common/components/postList/democracyExternalProposalsPostList/index.jsx, packages/next-common/components/postList/democracyExternalProposalsPostList/postItem.jsx, packages/next-common/components/profile/posted/list.js, packages/next/pages/democracy/externals/index.js
- refactor democracy external proposals post list
- use democracy external proposals post list in democracy external proposals page and user profile posted list
=> Refactor democracy external proposals post list, #6352

packages/next-common/components/postList/common/index.jsx, packages/next-common/components/postList/common/postItemTreasuryTag.jsx, packages/next-common/components/postList/councilMotionsPostList/index.jsx, packages/next-common/components/postList/councilMotionsPostList/postItem.jsx, packages/next-common/components/postList/democracyExternalProposalsPostList/postItem.jsx, packages/next-common/components/postList/democracyPublicProposalsPostList/postItem.jsx, packages/next-common/components/postList/democracyReferendaPostList/postItem.jsx, packages/next-common/components/postList/fellowshipReferendaPostList/postItem.jsx, packages/next-common/components/postList/post.jsx, packages/next-common/components/postList/treasuryChildBountiesPostList/postItem.jsx, packages/next-common/components/postList/treasuryProposalsPostList/postItem.jsx, packages/next-common/components/postList/treasurySpendsPostList/postItem.jsx, packages/next-common/components/postList/treasuryTipsPostList/postItem.jsx, packages/next-common/components/postList/treasyrybountiesPostList/postItem.jsx, packages/next-common/components/profile/posted/list.js, packages/next/pages/council/motions/index.js
- refactor council motions post list, remove logic in common post list
- use democracy public proposals post list in user profile posted page and democracy public proposals page
=> Refactor council motions post list, #6354

packages/collectives-next/pages/ambassador/tracks/[id].js, packages/next-common/components/layout/referendaLayout/trackNotFound.jsx, packages/next-common/components/notFound.js, packages/next-common/pages/fellowship/tracks/[id].js, packages/next/pages/referenda/tracks/[id]/index.js, packages/next/pages/referenda/tracks/[id]/statistics.js
- Referenda track detail
- Referenda track detail statistics tab
- Fellowship Referenda track detail
- Ambassador Referenda track detail
=> Show 404 component on track detail page, #6431
